# Generated by Django 2.1.1 on 2018-09-28 08:00

from django.db import migrations

CATEGORIES_DATA = [
    {'name': 'table'},
    {'name': 'sofa'},
    {'name': 'set'},
]

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('mainapp', 'Category')

    for data in CATEGORIES_DATA:
        Category.objects.get_or_create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180927_2338'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            lambda x,y: (x,y)
        )
    ]
