# Generated by Django 2.1.1 on 2018-09-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0003_auto_20180928_1300'),
        ('images', '0005_auto_20181225_1824')
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
            preserve_default=False,
        ),
    ]
