# Generated by Django 2.1.1 on 2018-10-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20181001_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descr',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descr',
            new_name='desc',
        ),
    ]
