# Generated by Django 2.1.3 on 2018-12-14 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0010_product_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'is_active']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'is_active', 'price']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
    ]
