# Generated by Django 2.1.3 on 2018-12-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20181214_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'is_active'], 'verbose_name_plural': 'Categories'},
        ),
    ]
