# Generated by Django 2.1.1 on 2018-10-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20181013_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
    ]
