# Generated by Django 2.1.1 on 2018-10-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20181013_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'modified', 'created'], 'permissions': (('analyse_model', 'Can analyse model'),)},
        ),
    ]
