# Generated by Django 2.1.3 on 2018-12-23 17:10

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0013_auto_20181223_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={'required': 'Укажите название товара'}, max_length=150, unique=True,
                                   verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8,
                                      validators=[mainapp.models.validate_positive], verbose_name='Цена'),
        ),
    ]
