# Generated by Django 2.1.3 on 2018-12-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20181223_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.SET_DEFAULT, to='images.Image'),
        ),
    ]
