# Generated by Django 2.1.1 on 2019-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20181225_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='spec_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Специальная скидка'),
        ),
    ]
