# Generated by Django 2.1.1 on 2019-01-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_category_spec_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['is_active', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['is_active', 'name', 'price']},
        ),
    ]
