# Generated by Django 2.1.1 on 2018-10-08 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_auto_20181001_1642'),
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product')},
        ),
    ]
