# Generated by Django 2.1.1 on 2018-10-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180930_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='value',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
