# Generated by Django 2.1.3 on 2018-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20181003_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='value',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
