# Generated by Django 2.1.3 on 2018-12-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20181003_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ['-is_superuser', 'username']},
        ),
    ]
