# Generated by Django 2.1.1 on 2019-01-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20181215_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ['-is_active', '-is_superuser', 'username']},
        ),
    ]
